#!/usr/bin/python3

# is a factors challenge

def factorize(n):
    for i in range(2, n // 2 + 1):
        if n % i:
            continue
        else:
            return i, n // i
    return n, 1

def main():
    with open('tests/test00', 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print(f'{n}={p}*{q}')

if __name__ == '__main__':
    main()
