#!/usr/bin/python3
# challenge

import math
import time

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def factorize(n):
    for i in range(2, n // 2 + 1):
        if is_prime(i) and is_prime(n // i) and n % i == 0:
            return i, n // i
    return n, 1

def main():
    with open('tests/rsa-16', 'r') as f:
        for line in f:
            n = int(line.strip())
            start_time = time.time()
            p, q = factorize(n)
            end_time = time.time()
            print(f'{n}={p}*{q} (time: {end_time - start_time:.6f}s)')

if __name__ == '__main__':
    main()
